hyperspace-testsuite closes #22
ComposableFi/hyperspace pull request #23
Opened 2022-08-30 07:40 UTC by seunlanlege

2022-08-30 11:03 UTC, blasrodri commented on tests/common/mod.rs
> +		let msg_create_client = MsgCreateAnyClient {
can this be wrapped into a helper func? It's done twice

2022-08-30 11:10 UTC, blasrodri commented on testsuite/src/lib.rs
> +	while let Some(ev) = chain_b_events.next().await {
a possible strategy here is to use:
- [skip_while](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.skip_while) 
- a timeout

2022-08-30 11:11 UTC, blasrodri commented
what have you done @seunlanlege ^_^

2022-08-30 11:15 UTC, seunlanlege commented on tests/common/mod.rs
> +		let msg_create_client = MsgCreateAnyClient {
yeah good catch

2022-08-30 11:16 UTC, seunlanlege commented on testsuite/src/lib.rs
> +	while let Some(ev) = chain_b_events.next().await {
I had actually used [StreamExt::any](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.any) but the future never terminated. Will investigate bringing it back.

2022-08-30 12:03 UTC, seunlanlege commented on testsuite/src/lib.rs
> +	while let Some(ev) = chain_b_events.next().await {
ended up using [StreamExt::take_while](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.take_while)

2022-08-31 09:07 UTC, Wizdave97 requested changes

2022-08-31 09:07 UTC, Wizdave97 commented on testsuite/tests/parachain_parachain.rs
> +		.submit_sudo_call(SetPalletParams {
We could delete the static call definitions and use the generated ones, since we have the parachain runtime auto generated.

2022-08-31 09:16 UTC, seunlanlege commented on testsuite/tests/parachain_parachain.rs
> +		.submit_sudo_call(SetPalletParams {
sounds good

2022-09-09 10:55 UTC, seunlanlege commented on parachain/src/provider.rs
> +		// };
After a lot of thinking, I don't wanna merge this pr until we have a to tell if we should update clients or not.

2022-09-09 10:56 UTC, seunlanlege commented on parachain/src/provider.rs
> +			.collect::<Result<Vec<_>, _>>()
let's just add this to config.

2022-09-09 10:56 UTC, seunlanlege commented on parachain/src/provider.rs
> +		dbg!(&balance);
```suggestion
```

2022-09-09 10:57 UTC, seunlanlege commented on parachain/src/provider.rs
> +		let balance = api.storage().tokens().accounts(&account, &CurrencyId(1), None).await?;
We'll need to coordinate with the substrate team on standardizing pallet-assets

2022-09-09 10:57 UTC, seunlanlege commented on parachain/src/provider.rs
> +	async fn timestamp_at(&self, block_number: u64) -> Result<u64, Self::Error> {
```suggestion
	async fn query_timestamp_at(&self, block_number: u64) -> Result<u64, Self::Error> {
```

I kinda like the naming convention we have going on lol

2022-09-09 10:58 UTC, seunlanlege commented on primitives/src/lib.rs
> +	async fn channel_whitelist(&self) -> Result<Vec<(ChannelId, PortId)>, Self::Error>;
Shouldn't it just be `ChannelId` ?

2022-09-09 10:59 UTC, seunlanlege commented on primitives/src/lib.rs
> +/// Implementation should work both for ordered and unordered channels
```suggestion
/// Returns undelivered packet sequences that have been sent out from
/// the `source` chain to the `sink` chain
/// Implementation should work both for ordered and unordered channels
```

2022-09-09 11:03 UTC, seunlanlege commented on primitives/src/lib.rs
> +/// Return undelivered packet acknowledgements
```suggestion
/// Queries the `source` chain for packet acknowledgements that have not been seen by the `sink` chain.
```

2022-09-09 11:05 UTC, seunlanlege commented on primitives/src/lib.rs
> +	}
I feel we can make this search `log₂` by doing a sort of binary search on the range of blocks. What do you think?

2022-09-09 11:06 UTC, seunlanlege commented on src/events.rs
> +			IbcEvent::SendPacket(send_packet) if parse_send_packets => {
let's add `cfg(test)` if this is the best way we can achieve this

2022-09-09 11:07 UTC, seunlanlege commented on src/events.rs
> +					continue
```suggestion
					// We can't send this packet immediately because of connection delays   
					continue
```

2022-09-09 11:08 UTC, seunlanlege commented on src/lib.rs
> +						chain_a.submit_ibc_messages(timeouts).await?;
I would like to put this whole thing behind a macro tbh

2022-09-09 11:11 UTC, seunlanlege commented on src/packet_messages.rs
> +				};
is there any way we can make this block more readable? 😵‍💫

2022-09-09 11:12 UTC, seunlanlege commented on src/packet_messages.rs
> +pub async fn query_ready_and_timed_out_packets(
is there any way we can make this whole function more readable? 😵‍💫

2022-09-09 11:13 UTC, seunlanlege commented on testsuite/tests/parachain_parachain.rs
> +	hyperspace_testsuite::send_packet_and_assert_acknowledgment(&chain_a, &chain_b, Some(handle)).await;
lets add a simple test for connection delays only as well, I understand that its covered in the timeout tests, but makes sense to test it without timouts

2022-09-09 12:29 UTC, Wizdave97 commented on primitives/src/lib.rs
> +	async fn channel_whitelist(&self) -> Result<Vec<(ChannelId, PortId)>, Self::Error>;
We need the port id to be able to fetch any details about a channel

2022-09-09 12:34 UTC, seunlanlege commented on primitives/src/lib.rs
> +	async fn channel_whitelist(&self) -> Result<Vec<(ChannelId, PortId)>, Self::Error>;
In that case then.

2022-09-09 14:54 UTC, Wizdave97 commented on primitives/src/lib.rs
> +	}
I'll look into how that can be done.

2022-09-09 14:57 UTC, Wizdave97 commented on src/packet_messages.rs
> +pub async fn query_ready_and_timed_out_packets(
Yeah, I'll  break it down into smaller functions.

2022-09-10 14:29 UTC, seunlanlege commented on Cargo.toml
> +#path = "tests/parachain/set_up_transfer_channel.rs"
```suggestion
```

2022-09-10 14:36 UTC, seunlanlege commented on src/lib.rs
> +}
Let's put this behind a mod

2022-09-12 08:50 UTC, Wizdave97 commented on parachain/src/provider.rs
> +		// };
I'll try out some ideas this week.

2022-09-12 13:42 UTC, seunlanlege commented on primitives/src/lib.rs
> +	} else {
absolutely beautiful ser

2022-09-12 13:45 UTC, seunlanlege commented on primitives/src/lib.rs
> +	} else {
Lets add a unit test for this using mocked data, what do you think?

2022-09-12 13:54 UTC, Wizdave97 commented on primitives/src/lib.rs
> +	} else {
Yeah, I was just thinking of that

2022-09-20 09:39 UTC, seunlanlege commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
isn't it possible that `max_height_for_timeouts` > `latest_finalized_block`? Because `query_finalized_parachain_headers_with_proof` will return an error in that case.

2022-09-20 09:40 UTC, seunlanlege commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
lets also add `max_height_for_timeouts` + `conn_delay` and add it to the `headers_with_events` only if it is < `latest_finalized_block `

2022-09-20 09:57 UTC, Wizdave97 commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
> max_height_for_timeouts
 `is_timeout_ update` is only true if the `finalized_blocks`  list already contains  `max_height_for_timeouts`,  so we won't run into that issue with `query_finalized_parachain_headers_with_proof`

2022-09-20 10:21 UTC, Wizdave97 commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
> `max_height_for_timeouts` + `conn_delay`

Why do we need to this? we are going to fetch the the proofs at `max_height_for_timeouts`, even after the connection delay has passed.

2022-09-20 10:28 UTC, seunlanlege commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
so here's how i'm visualizing whats happening

 - chainA recieves finality notification
 - chainA checks for maximum height for timed-out packets from chainB to chainA
 - chainA includes header update for this maximum height to chainB
 - we still can't timeout packets and have to update chainA's client on chainB past the connection delay

2022-09-20 10:31 UTC, seunlanlege commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
new protocol

- chainA recieves finality notification
- chainA checks for maximum height + connection_delay for timed-out packets from chainB to chainA
- chainA includes header update for this maximum height and maximum height + connection_delay to chainB
- we can now timeout chainB's packets to chainA

2022-09-20 11:06 UTC, Wizdave97 commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
The `maximum height + connection_delay` update doesn't need to exist on chainB to process the timeout packets,

This is how it's currently happening
* chainA recieves finality notification
* chainA checks for maximum height for timed-out packets from chainB to chainA
* chainA includes header update for this maximum height to chainB
* we still can't send timeout packets until the connection delay has passed for the `maximum height` header update
So we wait until the difference between time at which the maximum height header update was processed on chainB  and chainB's local timestamp is greater than the connection delay before sending the timeout packets,

we never use the update for `maximum height + connection_delay`  header to do anything.

2022-09-20 11:25 UTC, seunlanlege commented on parachain/src/provider.rs
> +			let max_height_for_timeouts = max_height_for_timeouts.unwrap();
> So we wait until the difference between time at which the maximum height header update was processed on chainB and chainB's latest timestamp is greater than the connection delay before sending the timeout packets,

Ahh this makes sense, thanks for clarifying.

2022-10-06 17:44 UTC, seunlanlege commented
superceded by composableFi/composable#1406

2022-10-06 17:44 UTC, closed without merging